# Generated by Django 4.0 on 2021-12-12 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_id', models.CharField(editable=False, max_length=32)),
                ('m_title', models.CharField(blank=True, max_length=80, null=True)),
                ('m_body', models.CharField(blank=True, max_length=50, null=True)),
                ('m_share_email_box', models.BooleanField(blank=True, default=False, null=True)),
                ('m_created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
