# Generated by Django 4.0 on 2021-12-14 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('contact_services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='m_id',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='m_receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='m_receiver_username', to='profiles.userprofile'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='m_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='m_sender_username', to='profiles.userprofile'),
        ),
    ]
