# Generated by Django 4.0 on 2022-02-02 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_services', '0004_alter_contactmessage_m_sender_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='m_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
