# Generated by Django 3.2 on 2022-03-23 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20220311_0644'),
        ('contact_services', '0005_contactmessage_m_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='m_receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='m_receiver_username', to='profiles.userprofile', verbose_name='To: '),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='m_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='m_sender_username', to='profiles.userprofile', verbose_name='Sender: '),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='m_sender_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email: '),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='m_sent',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Sent: '),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='m_share_email_box',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Would you like to share your email: '),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='m_title',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Title: '),
        ),
    ]
