# Generated by Django 3.2 on 2022-05-03 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_services', '0007_alter_contactmessage_m_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='m_body',
            field=models.CharField(blank=True, max_length=4000, null=True, verbose_name='Body: '),
        ),
    ]
