# Generated by Django 3.2 on 2022-03-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20220306_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_aka',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Preferred Name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_county',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='County'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_postcode',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_service',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name the service or the type of work you do'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_service_details',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Service or worker details'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_service_provider',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Are you a service provider?'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_town_or_city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Town or city'),
        ),
    ]
