# Generated by Django 4.0 on 2022-02-04 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact_services', '0005_contactmessage_m_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_order_number', models.CharField(editable=False, max_length=32)),
                ('s_title', models.CharField(blank=True, max_length=80, null=True)),
                ('s_created_date', models.DateTimeField(auto_now_add=True)),
                ('s_order_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('s_contact_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_services.contactmessage')),
                ('s_receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='s_receiver_username', to='contact_services.contactmessage')),
                ('s_sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='s_sender_username', to='contact_services.contactmessage')),
            ],
        ),
    ]
