# Generated by Django 3.2 on 2022-02-10 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedmessages',
            name='s_receiver',
        ),
        migrations.RemoveField(
            model_name='orderedmessages',
            name='s_sender',
        ),
        migrations.RemoveField(
            model_name='orderedmessages',
            name='s_title',
        ),
    ]
